/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.bcc.lpoo.om.gui.peca;

import br.edu.ifsul.bcc.lpoo.om.Controle;

/**
 *
 * @author Ygor
 */
public class JPanelPecaListagem extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPecaListagem
     */
     private Controle controle; 
    
    private JPanelPeca pnlPeca;
    
    /**
     * Creates new form JPanelPecaFormulario
     */
   
    public JPanelPecaListagem(JPanelPeca pnlPeca, Controle controle) {
        initComponents();
        this.pnlPeca = pnlPeca;
        this.controle = controle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        txfFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();
        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpListagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblFiltro.setText("Filtrar por nome:");
        pnlNorte.add(lblFiltro);

        txfFiltro.setColumns(10);
        txfFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFiltroActionPerformed(evt);
            }
        });
        pnlNorte.add(txfFiltro);

        btnFiltro.setText("Filtrar");
        pnlNorte.add(btnFiltro);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpListagem.setViewportView(tblListagem);

        pnlCentro.add(scpListagem);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txfFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFiltroActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        pnlPeca.showTela("tela_peca_formulario");


        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpListagem;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txfFiltro;
    // End of variables declaration//GEN-END:variables
}
